### ISSUE TITLE
Mapping between examples and source code?

### ISSUE THREAD

**Issue by denizdogan** [jasudev/AxisTabView#2]
Thanks again for this library, it's helping me out tremendously.

I was curious to know how I can find the mapping between each example in the README and its corresponding source code? I'm probably missing something obvious here.

For example, where is the source code for this one?

https://github.com/jasudev/AxisTabView/blob/main/Markdown/AxisTabView6.png

**Comment by jasudev** [comment]
Hi, If you run the Fabula (https://apps.apple.com/app/id1591155142) app, you can see it in the list.  thank you.
